#mybatis配置
mybatis:
  mapperLocations: classpath:mappers/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
#日志配置
logging:
  config: classpath:logback-spring.xml
  #redis 配置
  redis:
    host: 192.168.10.184
    port: 6389
    password: Redis235
    timeout: 1000ms #连接超时时长（毫秒）
    jedis:
      pool:
        max-wait: -1
        max-active: 1000
        max-idle: 10
        min-idle: 5
animals:
  animalsType:
    peopleProperties:
      name: gg
      age: 2
      sex: man
    animalsProperties:
      name: dd
      age: 1
      sex: male
