
spring:
  application:
    name: killer-demo
  profiles:
    active: local
  #redis 配置
  redis:
    host: 192.168.10.184
    port: 6389
    password: Redis235
    timeout: 1000ms #连接超时时长（毫秒）
    jedis:
      pool:
        max-wait: -1
        max-active: 1000
        max-idle: 10
        min-idle: 5
server:
  port: 8081